### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by eric-figueira** [eric-figueira/background-quotes#1]
- [x] Remove search author button
- [x] Create > Look for author > If doesn't exist, use a random one. If more than one matches the name, use first one. Show a dialog to inform
- [x] i18n
- [x] Better Results section
- [x] Add more fonts
- [x] Fix overflowing text in images
- [x] Responsive design
- [x] New READ.ME
- [x] Fix parameters on api
- [x] Better error handling (+ Translate error messages)
- [x] Fix language select default value
- [x] Waiting response skeleton
